### PR TITLE
Update C# implementation

### PR DESCRIPTION
**Pull request by ted-miller**
- Update to .Net 6.0
- Make the API thread-safe
- Mirror feature-set of the latest Java implementation

### CODE REVIEW

**Comment by ted-miller** [comment]
@EricMarcil, it looks like you are the maintainer of this branch. Let me know if there's someone else that I should ping with this.

**Comment by ted-miller** [comment]
@EricMarcil: @Aaron-Levan pointed out that we need to update the readme build instructions. Hold off on review/merge until we update that

**Comment by EricMarcil** [comment]
@ted-miller @Aaron-Levan I'm seeing commits updating to .net 6.0.  The T150 .net version is currently .net core 2.2 which was why we were targetting this version.

**Comment by ted-miller** [comment]
We are able to package the .net 6 runtime libraries with the extension executable. David confirmed that this is OK.

image

**Comment by EricMarcil** [comment]
@ted-miller I've checked with David, though it is possible to include, we would prefer to keep using Core 2.2 since that is already included in the SP.

> Regarding Ted's pull request on the SDK - I don't think we want to update the SDK to .NET 6 until the pendant supports it - and even then if people want to target SP3.0, they should use the SDK that targets .NET Core 2.2.  I can't imagine there is really any functionality in .NET 6 that isn't already in .NET 2 that we need just to call some thrift functions.

**Comment by ted-miller** [comment]
@davidljung @EricMarcil 
For clarification, are you saying that I'm supposed to develop all my stuff targeting 2.2, or just that you don't want the public SDK to target a version that is different than what is baked into the SP?

**Comment by davidljung** [comment]
@ted-miller - the latter: we'd like the SDK client code to target .NET 2.2 Core for now since that is what is on SP.  We can have client code for later .NET version in a side branch though.  I can't imagine there are any new features in .NET since 2.2 that would make a difference to the SDK classes that just wrap the Thrift generated client API.  We will support newer .NET version 'out of the box' in SP in future (we'll need to maintain container images for both for back compat.)

**Comment by ted-miller** [comment]
IIRC, the newer version of .Net requires a newer version of Thrift. When using the newer Thrift, the code it generates is using a bunch of async methods that significantly change how the code is structured.

Functionally, it's not any different than 2.2. But the actual code implementation does have some significant changes.

I'll close this PR and keep the code on my own fork for now.

**Pull request closed without merging**
